# Generated by Django 4.1.6 on 2023-03-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_groups_options_alter_tags_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Тэги заметок",
                null=True,
                related_name="notes_by_tag",
                to="myapp.tags",
            ),
        ),
    ]
