openapi: 3.0.2
info:
  title: Notes
  version: 1.0.0
  description: "API for all things \u2026"
paths:
  /api/notes/:
    get:
      operationId: listNotes
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Notes'
          description: ''
      tags:
      - Notes
    post:
      operationId: createNotes
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notes'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Notes'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Notes'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
          description: ''
      tags:
      - Notes
  /api/notes/{id}/:
    get:
      operationId: retrieveNotes
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this notes.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
          description: ''
      tags:
      - Notes
    put:
      operationId: updateNotes
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this notes.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notes'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Notes'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Notes'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
          description: ''
      tags:
      - Notes
    patch:
      operationId: partialUpdateNotes
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this notes.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notes'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Notes'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Notes'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notes'
          description: ''
      tags:
      - Notes
    delete:
      operationId: destroyNotes
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this notes.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - Notes
components:
  schemas:
    Notes:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        title:
          type: string
          maxLength: 64
        content:
          type: string
      required:
      - title
      - content
